
package WebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkflowServicePortType", targetNamespace = "webservices.services.weaver.com.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkflowServicePortType {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns WebService.WorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetWorkflowRequest")
    @ResponseWrapper(localName = "getWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetWorkflowRequestResponse")
    public WorkflowRequestInfo getWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getHendledWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetHendledWorkflowRequestList")
    @ResponseWrapper(localName = "getHendledWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetHendledWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getHendledWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns WebService.WorkflowRequestInfo
     */
    @WebMethod(operationName = "getWorkflowRequest4split", action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequest4split")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getWorkflowRequest4split", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetWorkflowRequest4Split")
    @ResponseWrapper(localName = "getWorkflowRequest4splitResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetWorkflowRequest4SplitResponse")
    public WorkflowRequestInfo getWorkflowRequest4Split(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.submitWorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "submitWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.SubmitWorkflowRequest")
    @ResponseWrapper(localName = "submitWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.SubmitWorkflowRequestResponse")
    public String submitWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        WorkflowRequestInfo in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        String in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        String in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestCount4OS")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getMyWorkflowRequestCount4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetMyWorkflowRequestCount4OS")
    @ResponseWrapper(localName = "getMyWorkflowRequestCount4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetMyWorkflowRequestCount4OSResponse")
    public int getMyWorkflowRequestCount4OS(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in2);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getTodoData")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getTodoData", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetTodoData")
    @ResponseWrapper(localName = "getTodoDataResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetTodoDataResponse")
    public String getTodoData(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestList4OS")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCCWorkflowRequestList4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCCWorkflowRequestList4OS")
    @ResponseWrapper(localName = "getCCWorkflowRequestList4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCCWorkflowRequestList4OSResponse")
    public ArrayOfWorkflowRequestInfo getCCWorkflowRequestList4OS(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in5);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getLeaveDays")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getLeaveDays", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetLeaveDays")
    @ResponseWrapper(localName = "getLeaveDaysResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetLeaveDaysResponse")
    public String getLeaveDays(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        String in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        String in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        String in4);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestList4Ofs")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getHendledWorkflowRequestList4Ofs", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetHendledWorkflowRequestList4Ofs")
    @ResponseWrapper(localName = "getHendledWorkflowRequestList4OfsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetHendledWorkflowRequestList4OfsResponse")
    public ArrayOfWorkflowRequestInfo getHendledWorkflowRequestList4Ofs(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in5);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowBaseInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowList")
    @ResponseWrapper(localName = "getCreateWorkflowListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowListResponse")
    public ArrayOfWorkflowBaseInfo getCreateWorkflowList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        int in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in5);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getProcessedWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetProcessedWorkflowRequestCount")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetProcessedWorkflowRequestCountResponse")
    public int getProcessedWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.doCreateRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "doCreateRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.DoCreateRequest")
    @ResponseWrapper(localName = "doCreateRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.DoCreateRequestResponse")
    public String doCreateRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        WorkflowRequestInfo in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.doCreateWorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "doCreateWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.DoCreateWorkflowRequest")
    @ResponseWrapper(localName = "doCreateWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.DoCreateWorkflowRequestResponse")
    public String doCreateWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        WorkflowRequestInfo in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestCount4OS")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getToDoWorkflowRequestCount4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToDoWorkflowRequestCount4OS")
    @ResponseWrapper(localName = "getToDoWorkflowRequestCount4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToDoWorkflowRequestCount4OSResponse")
    public int getToDoWorkflowRequestCount4OS(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in2);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.doForceOver")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "doForceOver", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.DoForceOver")
    @ResponseWrapper(localName = "doForceOverResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.DoForceOverResponse")
    public String doForceOver(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getProcessedWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetProcessedWorkflowRequestList")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetProcessedWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getProcessedWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns WebService.WorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowRequestInfo")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowRequestInfo", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowRequestInfo")
    @ResponseWrapper(localName = "getCreateWorkflowRequestInfoResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowRequestInfoResponse")
    public WorkflowRequestInfo getCreateWorkflowRequestInfo(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowBaseInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowTypeList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowTypeList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowTypeList")
    @ResponseWrapper(localName = "getCreateWorkflowTypeListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowTypeListResponse")
    public ArrayOfWorkflowBaseInfo getCreateWorkflowTypeList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestCount4Ofs")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getHendledWorkflowRequestCount4Ofs", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetHendledWorkflowRequestCount4Ofs")
    @ResponseWrapper(localName = "getHendledWorkflowRequestCount4OfsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetHendledWorkflowRequestCount4OfsResponse")
    public int getHendledWorkflowRequestCount4Ofs(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in2);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestList4OS")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getMyWorkflowRequestList4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetMyWorkflowRequestList4OS")
    @ResponseWrapper(localName = "getMyWorkflowRequestList4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetMyWorkflowRequestList4OSResponse")
    public ArrayOfWorkflowRequestInfo getMyWorkflowRequestList4OS(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in5);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestList4OS")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getProcessedWorkflowRequestList4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetProcessedWorkflowRequestList4OS")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestList4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetProcessedWorkflowRequestList4OSResponse")
    public ArrayOfWorkflowRequestInfo getProcessedWorkflowRequestList4OS(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in5);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getForwardWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getForwardWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetForwardWorkflowRequestCount")
    @ResponseWrapper(localName = "getForwardWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetForwardWorkflowRequestCountResponse")
    public int getForwardWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getToDoWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToDoWorkflowRequestCount")
    @ResponseWrapper(localName = "getToDoWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToDoWorkflowRequestCountResponse")
    public int getToDoWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.givingOpinions")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "givingOpinions", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GivingOpinions")
    @ResponseWrapper(localName = "givingOpinionsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GivingOpinionsResponse")
    public String givingOpinions(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        String in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCCWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCCWorkflowRequestList")
    @ResponseWrapper(localName = "getCCWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCCWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getCCWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestCount4OS")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getProcessedWorkflowRequestCount4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetProcessedWorkflowRequestCount4OS")
    @ResponseWrapper(localName = "getProcessedWorkflowRequestCount4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetProcessedWorkflowRequestCount4OSResponse")
    public int getProcessedWorkflowRequestCount4OS(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in2);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getBeRejectWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getBeRejectWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetBeRejectWorkflowRequestCount")
    @ResponseWrapper(localName = "getBeRejectWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetBeRejectWorkflowRequestCountResponse")
    public int getBeRejectWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.forward2WorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "forward2WorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.Forward2WorkflowRequest")
    @ResponseWrapper(localName = "forward2WorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.Forward2WorkflowRequestResponse")
    public String forward2WorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        String in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        String in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getAllWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getAllWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetAllWorkflowRequestList")
    @ResponseWrapper(localName = "getAllWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetAllWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getAllWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getToDoWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToDoWorkflowRequestList")
    @ResponseWrapper(localName = "getToDoWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToDoWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getToDoWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestCount4OS")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCCWorkflowRequestCount4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCCWorkflowRequestCount4OS")
    @ResponseWrapper(localName = "getCCWorkflowRequestCount4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCCWorkflowRequestCount4OSResponse")
    public int getCCWorkflowRequestCount4OS(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in2);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getHendledWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetHendledWorkflowRequestCount")
    @ResponseWrapper(localName = "getHendledWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetHendledWorkflowRequestCountResponse")
    public int getHendledWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestList4OS")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getToDoWorkflowRequestList4OS", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToDoWorkflowRequestList4OS")
    @ResponseWrapper(localName = "getToDoWorkflowRequestList4OSResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToDoWorkflowRequestList4OSResponse")
    public ArrayOfWorkflowRequestInfo getToDoWorkflowRequestList4OS(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in5);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToBeReadWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getToBeReadWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToBeReadWorkflowRequestCount")
    @ResponseWrapper(localName = "getToBeReadWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToBeReadWorkflowRequestCountResponse")
    public int getToBeReadWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowCount")
    @ResponseWrapper(localName = "getCreateWorkflowCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowCountResponse")
    public int getCreateWorkflowCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.forwardWorkflowRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "forwardWorkflowRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.ForwardWorkflowRequest")
    @ResponseWrapper(localName = "forwardWorkflowRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.ForwardWorkflowRequestResponse")
    public String forwardWorkflowRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        String in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        String in4);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getToBeReadWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getToBeReadWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToBeReadWorkflowRequestList")
    @ResponseWrapper(localName = "getToBeReadWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetToBeReadWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getToBeReadWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in5);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getBeRejectWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getBeRejectWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetBeRejectWorkflowRequestList")
    @ResponseWrapper(localName = "getBeRejectWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetBeRejectWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getBeRejectWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCCWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCCWorkflowRequestCount")
    @ResponseWrapper(localName = "getCCWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCCWorkflowRequestCountResponse")
    public int getCCWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getAllWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getAllWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetAllWorkflowRequestCount")
    @ResponseWrapper(localName = "getAllWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetAllWorkflowRequestCountResponse")
    public int getAllWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getDoingWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getDoingWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetDoingWorkflowRequestCount")
    @ResponseWrapper(localName = "getDoingWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetDoingWorkflowRequestCountResponse")
    public int getDoingWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getForwardWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getForwardWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetForwardWorkflowRequestList")
    @ResponseWrapper(localName = "getForwardWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetForwardWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getForwardWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getMyWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetMyWorkflowRequestList")
    @ResponseWrapper(localName = "getMyWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetMyWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getMyWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getMyWorkflowRequestCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetMyWorkflowRequestCount")
    @ResponseWrapper(localName = "getMyWorkflowRequestCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetMyWorkflowRequestCountResponse")
    public int getMyWorkflowRequestCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns WebService.ArrayOfString
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowNewFlag")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getWorkflowNewFlag", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetWorkflowNewFlag")
    @ResponseWrapper(localName = "getWorkflowNewFlagResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetWorkflowNewFlagResponse")
    public ArrayOfString getWorkflowNewFlag(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.writeWorkflowReadFlag")
    @RequestWrapper(localName = "writeWorkflowReadFlag", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.WriteWorkflowReadFlag")
    @ResponseWrapper(localName = "writeWorkflowReadFlagResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.WriteWorkflowReadFlagResponse")
    public void writeWorkflowReadFlag(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowTypeCount")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getCreateWorkflowTypeCount", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowTypeCount")
    @ResponseWrapper(localName = "getCreateWorkflowTypeCountResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetCreateWorkflowTypeCountResponse")
    public int getCreateWorkflowTypeCount(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestLog
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequestLogs")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getWorkflowRequestLogs", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetWorkflowRequestLogs")
    @ResponseWrapper(localName = "getWorkflowRequestLogsResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetWorkflowRequestLogsResponse")
    public ArrayOfWorkflowRequestLog getWorkflowRequestLogs(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        int in4);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.deleteRequest")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "deleteRequest", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.DeleteRequest")
    @ResponseWrapper(localName = "deleteRequestResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.DeleteRequestResponse")
    public boolean deleteRequest(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getUserid")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getUserId", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetUserIdResponse")
    public String getUserId(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        String in1);

    /**
     * 
     * @param in5
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns WebService.ArrayOfWorkflowRequestInfo
     */
    @WebMethod(action = "urn:weaver.workflow.webservices.WorkflowService.getDoingWorkflowRequestList")
    @WebResult(name = "out", targetNamespace = "webservices.services.weaver.com.cn")
    @RequestWrapper(localName = "getDoingWorkflowRequestList", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetDoingWorkflowRequestList")
    @ResponseWrapper(localName = "getDoingWorkflowRequestListResponse", targetNamespace = "webservices.services.weaver.com.cn", className = "WebService.GetDoingWorkflowRequestListResponse")
    public ArrayOfWorkflowRequestInfo getDoingWorkflowRequestList(
        @WebParam(name = "in0", targetNamespace = "webservices.services.weaver.com.cn")
        int in0,
        @WebParam(name = "in1", targetNamespace = "webservices.services.weaver.com.cn")
        int in1,
        @WebParam(name = "in2", targetNamespace = "webservices.services.weaver.com.cn")
        int in2,
        @WebParam(name = "in3", targetNamespace = "webservices.services.weaver.com.cn")
        int in3,
        @WebParam(name = "in4", targetNamespace = "webservices.services.weaver.com.cn")
        ArrayOfString in4,
        @WebParam(name = "in5", targetNamespace = "webservices.services.weaver.com.cn")
        boolean in5);

}
